### ISSUE TITLE
停止并删除未经授权使用的代码

### ISSUE THREAD

**Issue by gc-copyright** [Daoting/dt#102]
尊敬的Daoting,

我们注意到，在未经授权的情况下, 你的代码库中包含了我司的部分产品源代码。
这些代码受相关知识产权法律的保护，未经授权的使用，已经构成了对我司的明确侵权。

我们要求您立即：
- 停止使用所有侵权代码。
- 从你的代码库中删除侵权代码。

如果您在7日内未能遵守这些要求，我们将采取进一步的法律行动来保护我们的知识产权。这可能包括但不仅限于经济赔偿。
感谢您对这一严重问题的关注。

**Comment by Daoting** [comment]
不知道是不是Excel控件的模型部分代码，整个Infras目录已删！

**Comment by gc-copyright** [comment]
谢谢你的配合。  我们将撤销其它渠道的侵权调查。
