### ISSUE TITLE
[wasm] FileItem上传、分享、MediaPlayerElement等功能未实现

### ISSUE THREAD

**Issue by Daoting** [Daoting/dt#15]

**Comment by sunl158** [comment]
首先感谢，请优先安排！

**Comment by Daoting** [comment]
好的，MediaPlayerElement得等到 winappsdk 1.2

**Comment by Daoting** [comment]
已实现上传；
不支持分享；
MediaPlayerElement 合并到 https://github.com/Daoting/dt/issues/7
