### ISSUE TITLE
编译和运行

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#66]
@Daoting ，我运行Win版本遇到提示安装frameworks for .net 错误。尝试按照了很多版本的.net仍然不成功。能否加一下我的QQ 325024666 或 15821005460 微信，协助一下。谢谢啦。我尝试一天了，都没能运行起来。

**Comment by Daoting** [comment]
我当前的开发环境：VS17.3.0 Preview 6.0，因为android ios需要用到maui，而稳定版还没有发布，所以问题比较多，包括uno plateform也是在预览版上，VS17.3正式版估计就这几天发布吧。

安装VS17.3.0 Preview后请参见 https://github.com/unoplatform/uno/discussions/7833 检查一下开发环境，通过了再试一下能运行不，有问题咱们再详细讨论。

**Comment by sunl158** [comment]
我对这个dt项目非常感兴趣，可是尝试了一周了，各种编译何运行问题，升级到了稳定版，昨天发布的，仍然Android不能编译通过，UWP能通过，但是不能运行。我也尝试了.Net 5的版本，UWP运行良好，Android存在闪退情况，把Debug常量去掉，好了很多。但是WASM版本,Sqlite看不太明白，不过屏蔽Sqlite倒是能运行。不过我还是希望在最新的版本上运行，实在非常郁闷。若您有时间，可否协助一下。若能够完整开发出应用，我一定紧密配合这个开源项目的测试，完善。目前发现在WASM能运行，但是速度确实比Andorid，UWP慢一些

**Comment by sunl158** [comment]
另外，我想问一下，您下一步的计划，是否是通过Dt.MAUI支持 (移动端+UWP),保留Dt.Shell.WASM版本。似乎MAUI并不支持XAML Web开发。期待一个下载，编译正常的版本

**Comment by sunl158** [comment]
使用Uno-Check 报错，请求的名称有效，但是找不到请求的类型的数据（raw.githubusercontent.com:443)

**Comment by Daoting** [comment]
谢谢支持！
Android不能编译通过可能因为引用包重复的问题，我碰到过， 需要手动删除些配置，我找一下告诉你。

**Comment by sunl158** [comment]
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: 
Compilation failed to complete, origin: C:\Users\sunli\.nuget\packages\xamarin.jetbrains.annotations\23.0.0.3\buildTransitive\net6.0-android31.0\..\..\jar\org.jetbrains.annotations-23.0.0.jar :
 org/jetbrains/annotations/Range.class	Dt.Shell.Droid	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.D8.targets	79

**Comment by Daoting** [comment]
一直在跟进preview版本，问题非常多，弄的很累。
准备在 VS 17.3 + uno 4.5 稳定环境上完善dt，暂时支持 winui android ios wasm 四个平台。
wasm的pwa很让人期望，存在的问题是初次下载文件大、速度慢，但比最初快太多了，值得期待但尽量不用在生成环境！
android ios的很成熟了，放心使用。

**Comment by Daoting** [comment]
android升级rc2后 Square.OkHttp3 中引用的包 xamarin.kotlin.stdlib  和 xamarin.jetbrains.annotations 重复复制jar包的现象，删除以下文件的include
C:\Users\xxx\\.nuget\packages\xamarin.kotlin.stdlib\1.6.20.1\buildTransitive\net6.0-android31.0\Xamarin.Kotlin.StdLib.targets
C:\Users\xxx\\.nuget\packages\xamarin.jetbrains.annotations\23.0.0.3\buildTransitive\net6.0-android31.0\Xamarin.Jetbrains.Annotations.targets 

xxx为你的用户名

**Comment by sunl158** [comment]
<NetCoreWasmSDKUri>d:\dt\Package\wasm\dotnet-runtime-wasm-windows-bd114dd-53ca85fb900-1877706367-Sqlite.zip</NetCoreWasmSDKUri>

**Comment by sunl158** [comment]
删除了您说的两个文件，android编译通过了。实在能理解您的付出。另外，这个文件，我是看您文档，仍然没有弄明白如何制作....能直接放到GitHub上吗？还是必须每个设备自己产生？ d:\dt\Package\wasm\dotnet-runtime-wasm-windows-bd114dd-53ca85fb900-1877706367-Sqlite.zip

**Comment by Daoting** [comment]
文件41M太大，这里发不了，发邮箱吧

**Comment by sunl158** [comment]
sun.light@live.cn

**Comment by sunl158** [comment]
非常感谢，激动人心的时刻就快到来了

**Comment by sunl158** [comment]
虽然邮件还在路上，好像没有赞助链接，我想发个小红包表达表达心意

**Comment by Daoting** [comment]
谢谢啊，我这纯属情怀，绝对100%认真！

**Comment by Daoting** [comment]
加你微信吧，试了两个邮箱附件太大

**Comment by sunl158** [comment]
.Net 6版本修复了excel饼图的bug修复了，现在好了。微信是 15821005460
