### ISSUE TITLE
若dt-Fsm服务不在线，客户端调用AtFsm.IsFileExists会崩溃

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#77]
\Client\Dt.Base\FileList\FileItem.cs
internal async Task<bool> Download(bool p_priorThumbnail = false, bool p_prompt = true)
 if (p_priorThumbnail)
            {
                // 优先下载缩略图时，先判断是否存在
                downloadThumb = await AtFsm.IsFileExists(ID + ThumbPostfix);
                // 缩略图不存在时，若为视频文件不下载
                if (!downloadThumb && FileType != FileItemType.Image)
                    return false;
            }
在调用服务时，因为服务经常断线，在访问不到时，UWP客户端会崩溃。当然，可以自己增加TryCatch,但是是否与全局的Exection 处理方式有关

**Comment by Daoting** [comment]
1. 目前win客户端所有http请求异常时都会崩溃，统一抛出ServerException，每个都TryCatch太啰嗦，崩溃原因：https://github.com/Daoting/dt/issues/1
2. uwp客户端已移到https://github.com/daoting/dt-uwp ，现在是Winappsdk + WinUI，简称win客户端
