### ISSUE TITLE
[win] <UseMauiEssentials>true</UseMauiEssentials>

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#78]
编译正常，运行遇到问题，You must install or update .Net to Run this application.
Framework:'Microsoft.Manui.Essentials',version '**FromWorkload**'(x64)

**Comment by Daoting** [comment]
uwp客户端已移到https://github.com/daoting/dt-uwp ，现在是Winappsdk + WinUI，简称win！

问题怎么重现？

**Comment by sunl158** [comment]
从代码服务器上下载的，只要Dt.Shell.Win 包含了Import Common.pros 在运行时候，就会有错误发现
<Import Project="..\Common.props" />

***@***.***

**Comment by Daoting** [comment]
一直没碰到这种现象，Microsoft.Manui.Essentials 需要maui，vs2022安装，都采用默认选项
![image](https://user-images.githubusercontent.com/29876815/199131604-6b614473-67cf-4db6-803c-5fa6e2be7902.png)
