### ISSUE TITLE
public the All in SqliteDbs 

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#79]
请将SqliteDbs 中的All,公开，以便自定义不同位置的本地库。
另外 SqliteProvider.OpenDb,也请允许定义在不同位置(非Kit.DataPath)，不同后缀的，如.s3db,的本地库

**Comment by Daoting** [comment]
为方便使用，SqliteProvider<Sqlite_name> 的方法都为static，巧妙的使用了泛型类型名称，用时只需 AtXx.Query 的方式即可，无需new等啰嗦的写法，简单方便够用。

若有特殊需求可参照SqliteProvider另外实现，SqliteConnectionEx SqliteCommandEx都可复用。
