### ISSUE TITLE
是否可以参考Uno,修正 WASM下HttpClient BaseRpc.Wasm.HttpClient

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#80]
static BaseRpc()
 

#elif WASM
            _client = new HttpClient();
#endif
 Uno.UI.Wasm.WasmHttpHandler handler=new Uno.UI.Wasm.WasmHttpHandler(); 
 using (handler)
				using (var client = new HttpClient(handler))
经测试是可以的

**Comment by Daoting** [comment]
WasmHttpHandler没有实质功能
