### ISSUE TITLE
子项目有错误，应用异常退出

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#84]
如下，其中一个子功能，xaml定义有问题缺少Tab,会造成整个程序退出，而不是单独此页面不能打开
<a:Win x:Class="XX.AM02R"
         xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:TYW="using:TYWUI"     
         xmlns:FU="using:fifoUI"  
        >
    <a:Main>
        <FU:ZAA x:Name="cMain"   />
    </a:Main>
</a:Win>

**Comment by Daoting** [comment]
原来抛出异常，调整为提示：

![image](https://user-images.githubusercontent.com/29876815/204425522-ba2bb7e8-7b5e-4884-8cf3-aa472ddba3d0.png)
