### ISSUE TITLE
Table Cone and Copy

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#88]
是否可以在Clone不复制数据，仅复制空表(Table.cs 531行复制了数据)
，增加Copy方法，复制结构与数据

**Comment by Daoting** [comment]
静态方法 Table.Create

![image](https://user-images.githubusercontent.com/29876815/205008756-95a41b4b-7d6a-4bfe-8cea-2150de0c494c.png)


![image](https://user-images.githubusercontent.com/29876815/205009693-49713f25-7692-4585-9574-b1abe0aaf004.png)
