### ISSUE TITLE
Fv 下面元素，若直接使用StackPanel 而外层不增加CFree,会造成整个系统退出

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#89]
似乎增加CFree也不支持StackPanel 排版.请考虑支持，并非所有字段都需要占用相同宽度
<a:Fv x:Name="dlgMaster">
                
                        <StackPanel Orientation="Vertical">
                            <a:CText ID="AMNRKRS" Title="设备"/>
                            <a:CText ID="AMLFDNR" ShowTitle="False" />
                            <a:CText ID="AMPOS"  ShowTitle="False"/>
                        </StackPanel>

**Comment by Daoting** [comment]
设计的初衷就是表单和格是一体的，Fv支持自适应宽度，为保证PhoneUI和WinUI统一。

有特殊需求就用系统控件吧。
