### ISSUE TITLE
FuzzySearch .LoadHisItems 修改为 async Task

### ISSUE THREAD

**Issue by sunl158** [Daoting/dt#97]
请问，是否有必要 将 async void LoadHisItems()方法，改为   async Task LoadHisItems()。否则在调用的地方，会不等待查询结果返回。有很多次的界面死锁，发生在使用FuzzySearch 界面，但是并不稳定出现。这个界面有个特点，是需要用SQLite装载历史记录。或许与此有关。

**Comment by Daoting** [comment]
可以修改为 `async Task LoadHisItems()`，私有方法不会影响外部，帮忙观察一下是否还有界面死锁现象。
@sunl158
